//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPhotoBoothAI.Application.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPhotoBoothAI.Application.Assets.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywna.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ramkę.
        /// </summary>
        public static string addFrame {
            get {
                return ResourceManager.GetString("addFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj grupę.
        /// </summary>
        public static string addGroup {
            get {
                return ResourceManager.GetString("addGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zdjęcie.
        /// </summary>
        public static string addPhoto {
            get {
                return ResourceManager.GetString("addPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj szablon.
        /// </summary>
        public static string addTemplate {
            get {
                return ResourceManager.GetString("addTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesłona.
        /// </summary>
        public static string aperture {
            get {
                return ResourceManager.GetString("aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój aparat.
        /// </summary>
        public static string cameraName {
            get {
                return ResourceManager.GetString("cameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparat.
        /// </summary>
        public static string cameraSettings {
            get {
                return ResourceManager.GetString("cameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz format.
        /// </summary>
        public static string chooseFormat {
            get {
                return ResourceManager.GetString("chooseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść layout.
        /// </summary>
        public static string clearLayout {
            get {
                return ResourceManager.GetString("clearLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiel.
        /// </summary>
        public static string clone {
            get {
                return ResourceManager.GetString("clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunąć grupę?.
        /// </summary>
        public static string deleteGroup {
            get {
                return ResourceManager.GetString("deleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunąć grupę i wszystkie szablony?.
        /// </summary>
        public static string deleteGroupDesc {
            get {
                return ResourceManager.GetString("deleteGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wydruku. Aby wyświetlić tło dodaj obraz do powyższej listy.
        /// </summary>
        public static string designCanvasText {
            get {
                return ResourceManager.GetString("designCanvasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz format do edycji.
        /// </summary>
        public static string editFormat {
            get {
                return ResourceManager.GetString("editFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string en_EN {
            get {
                return ResourceManager.GetString("en-EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warstwa ramek.
        /// </summary>
        public static string frameLayer {
            get {
                return ResourceManager.GetString("frameLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupy.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iso.
        /// </summary>
        public static string iso {
            get {
                return ResourceManager.GetString("iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby przełączać się między layoutami wybierz przycisk z oznaczeniem layoutu który chcesz edytować..
        /// </summary>
        public static string layoutDescription_0 {
            get {
                return ResourceManager.GetString("layoutDescription_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouty wydruków pozwalają na personalizację wyglądu wydruków. Po dodaniu tła zostanie ono automatycznie załadowane do layoutu wydruku. Przycisk „Następne tło” służy do przełączania się między dodanymi tłami..
        /// </summary>
        public static string layoutDescription_1 {
            get {
                return ResourceManager.GetString("layoutDescription_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby zmieniać ilość zdjęć w serii korzystaj z opcji „Dodaj zdjęcie” oraz „Usuń zdjęci”. Aby manipulować pozycją, rozmiarem oraz pochyleniem zdjęcia, przełącz się na warstwę zdjęć, aktywna warstwa jest oznaczona kolorowym kółkiem Pozycję zmienisz za pomocą ruchu myszy. Kąt pochylenia zdjęcia zmienisz kółkiem myszy, a jego rozmiar za pomocą klawisza CTRL oraz kółka myszy. Dodatkowo SHIFT zwiększa stopień powiększania i zmniejszania..
        /// </summary>
        public static string layoutDescription_2 {
            get {
                return ResourceManager.GetString("layoutDescription_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warstwa ramek służy do projektowania warstwy nakładanej na zdjęci. Do warstwy ramek można dodawać różnego rodzaju grafiki (np. serca, baloniki). Ta warstwa pozwala uzyskać efekt głębi wydruku. Aby dodać elementy do warstwy ramek, przełącz się na nią. Aktywna warstwa jest oznaczona kolorowym kółkiem. Użyj przycisku &quot;Dodaj ramkę&quot; i w nowym oknie wskaż plik lub przeciągnij myszką plik graficzny na pole podglądu layoutu. Aby usunąć element kliknij na nim prawym przyciskiem myszy i wybierz opcję Usuń.
        /// </summary>
        public static string layoutDescription_3 {
            get {
                return ResourceManager.GetString("layoutDescription_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zakończeniu edycji zapisz swoje ustawienia. Nie zapisanie ustawień spowoduję utratę wszelkim zmian. Wyczyszczenie warstw spowoduję usunięcie wszystkich zdjęć w serii, elementów grafiki z warstwy ramek oraz ich ustawień.
        /// </summary>
        public static string layoutDescription_4 {
            get {
                return ResourceManager.GetString("layoutDescription_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa grupa.
        /// </summary>
        public static string newGroup {
            get {
                return ResourceManager.GetString("newGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następne tło.
        /// </summary>
        public static string nextBackground {
            get {
                return ResourceManager.GetString("nextBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zapisanie zmian spowoduję ich utratę. Czy kontynuować?.
        /// </summary>
        public static string notSavedChangesMessage {
            get {
                return ResourceManager.GetString("notSavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zapisane zmiany.
        /// </summary>
        public static string notSavedChangesTittle {
            get {
                return ResourceManager.GetString("notSavedChangesTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz plik.
        /// </summary>
        public static string openFile {
            get {
                return ResourceManager.GetString("openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warstwa zdjęć.
        /// </summary>
        public static string photoLayer {
            get {
                return ResourceManager.GetString("photoLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string pl_PL {
            get {
                return ResourceManager.GetString("pl-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocztówka.
        /// </summary>
        public static string postcard {
            get {
                return ResourceManager.GetString("postcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout wydruku.
        /// </summary>
        public static string printLayout {
            get {
                return ResourceManager.GetString("printLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zdjęcie.
        /// </summary>
        public static string removePhoto {
            get {
                return ResourceManager.GetString("removePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom ponownie.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiany zostaną zastsowane po ponownym uruchomieniu aplikacji.
        /// </summary>
        public static string restartRequired {
            get {
                return ResourceManager.GetString("restartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano zmiany.
        /// </summary>
        public static string savedChanges {
            get {
                return ResourceManager.GetString("savedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz layout.
        /// </summary>
        public static string saveLayout {
            get {
                return ResourceManager.GetString("saveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość migawki.
        /// </summary>
        public static string shutterSpeed {
            get {
                return ResourceManager.GetString("shutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz podgląd.
        /// </summary>
        public static string startLiveView {
            get {
                return ResourceManager.GetString("startLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listek.
        /// </summary>
        public static string stripe {
            get {
                return ResourceManager.GetString("stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrób zdjęcie.
        /// </summary>
        public static string takePhoto {
            get {
                return ResourceManager.GetString("takePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablony.
        /// </summary>
        public static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balans bieli.
        /// </summary>
        public static string whiteBalance {
            get {
                return ResourceManager.GetString("whiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwe proporcje obrazu, obraz zostanie rozciągnięty, aby dopasować się do obszaru wydruku. Czy mimo to chcesz dodać obraz do listy teł?.
        /// </summary>
        public static string wrongImageRatioMessage {
            get {
                return ResourceManager.GetString("wrongImageRatioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwe proporcję obrazu.
        /// </summary>
        public static string wrongImageRatioTitle {
            get {
                return ResourceManager.GetString("wrongImageRatioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
