name: dotnet build

on: [push]

env:
  SOLUTION: MPhotoBoothAI.sln

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup emgucv
        run: sudo apt install build-essential libgtk-3-dev libgstreamer1.0-dev libavcodec-dev libswscale-dev libavformat-dev libdc1394-dev libv4l-dev cmake-curses-gui ocl-icd-dev freeglut3-dev libgeotiff-dev libusb-1.0-0-dev libvtk9-dev libfreetype-dev libharfbuzz-dev qtbase5-dev libeigen3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgflags-dev libgoogle-glog-dev liblapacke-dev libva-dev
     
      - name: Add Motiony nugets
        run: dotnet nuget add source --username matihuf@hotmail.com --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Motiony/index.json"

      - name: Build Project
        run: dotnet build ${{ env.SOLUTION }} --configuration Release

      - name: Tests
        run: dotnet test ${{ env.SOLUTION }}  --filter TestCategory=Unit --configuration Release --no-restore --no-build